# Site settings
title: Se Repos - Used for troubleshooting Se Issues
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Static pages for troubleshooting encountered Se issues.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: trabulmonkee
github_username:  trabulmonkee

# Build settings
markdown: kramdown
